### ISSUE TITLE
Schema for nested comments. (reply feature)

### ISSUE THREAD

**Issue by AksR2** [thimansh/myreddit#15]
comments -> post -> subreddit (schema)
with level number for each comment and user associated with that comment.
Level numbers will help render comments.
we will also have user field with the comment and replied_to(which also has a username) to correctly render the nested comment structure.

**Comment by prachipdesai** [comment]
To insert a comment for a system with threaded comments, there is a need of slug path and full_slug at insert. Working on that currently and the compound index to maximize the performance of the queries via direct links

**Comment by thimansh** [comment]
flattening the structure instead of nested comments
