### ISSUE TITLE
New Issue: Firebase update version 4 to 5

### ISSUE THREAD

**Issue by thimansh** [thimansh/myreddit#7]
Namespace 'firebase' has no exported member 'Promise'.

**Comment by AksR2** [comment]
Using the older version for now the version is  4.4.0
Command to downgrade 
npm install angularfire2 firebase4.4.0 --save
Incase you clone the project that is the command you will need

**Comment by AksR2** [comment]
Firebase was removed. Shifted to MongoDB for better support and robustness.
